name: 'lever_integration_tests'
version: '0.1.0'
config-version: 2
profile: 'integration_tests'


vars:
  lever_source:
    application: "{{ ref('application') }}"
    archive_reason: "{{ ref('archive_reason') }}"
    feedback_form: "{{ ref('feedback_form') }}"
    feedback_form_field: "{{ ref('feedback_form_field') }}"
    interview_feedback: "{{ ref('interview_feedback') }}"
    interview: "{{ ref('interview') }}"
    interviewer_user: "{{ ref('interviewer_user') }}"
    offer: "{{ ref('offer') }}"
    opportunity_source: "{{ ref('opportunity_source') }}"
    opportunity_stage_history: "{{ ref('opportunity_stage_history') }}"
    opportunity_tag: "{{ ref('opportunity_tag') }}"
    opportunity: "{{ ref('opportunity') }}"
    posting_interview: "{{ ref('posting_interview') }}"
    posting_tag: "{{ ref('posting_tag') }}"
    posting: "{{ ref('posting') }}"
    requisition_posting: "{{ ref('requisition_posting') }}"
    requisition_offer: "{{ ref('requisition_offer') }}"
    requisition: "{{ ref('requisition') }}"
    stage: "{{ ref('stage') }}"
    user: "{{ ref('user') }}"
    contact_email: "{{ ref('contact_email') }}"
    contact_phone: "{{ ref('contact_phone') }}"
    contact_link: "{{ ref('contact_link') }}"
    resume: "{{ ref('resume') }}"

  lever:
    application: "{{ ref('stg_lever__application') }}"
    archive_reason: "{{ ref('stg_lever__archive_reason') }}"
    feedback_form: "{{ ref('stg_lever__feedback_form') }}"
    feedback_form_field: "{{ ref('stg_lever__feedback_form_field') }}"
    interview_feedback: "{{ ref('stg_lever__interview_feedback') }}"
    interview: "{{ ref('stg_lever__interview') }}"
    interviewer_user: "{{ ref('stg_lever__interviewer_user') }}"
    offer: "{{ ref('stg_lever__offer') }}"
    opportunity_source: "{{ ref('stg_lever__opportunity_source') }}"
    opportunity_stage_history: "{{ ref('stg_lever__opportunity_stage_history') }}"
    opportunity_tag: "{{ ref('stg_lever__opportunity_tag') }}"
    opportunity: "{{ ref('stg_lever__opportunity') }}"
    posting_interview: "{{ ref('stg_lever__posting_interview') }}"
    posting_tag: "{{ ref('stg_lever__posting_tag') }}"
    posting: "{{ ref('stg_lever__posting') }}"
    requisition_posting: "{{ ref('stg_lever__requisition_posting') }}"
    requisition_offer: "{{ ref('stg_lever__requisition_offer') }}"
    requisition: "{{ ref('stg_lever__requisition') }}"
    stage: "{{ ref('stg_lever__stage') }}"
    user: "{{ ref('stg_lever__user') }}"
    contact_email: "{{ ref('stg_lever__contact_email') }}"
    contact_phone: "{{ ref('stg_lever__contact_phone') }}"
    contact_link: "{{ ref('stg_lever__contact_link') }}"
    resume: "{{ ref('stg_lever__resume') }}"

seeds:
  lever_integration_tests:
    +column_types:
      _fivetran_synced: timestamp
    application:
      +column_types:
        archived_at: timestamp
        created_at: timestamp
    feedback_form:
      +column_types:
        completed_at: timestamp
        created_at: timestamp
        deleted_at: timestamp
    feedback_form_field:
      +column_types:
        field_index: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        value_index: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        value_date: timestamp
        value_decimal: numeric
    interview:
      +column_types:
        canceled_at: timestamp
        created_at: timestamp
        date: timestamp
        duration: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    offer:
      +column_types:
        created_at: timestamp
    opportunity:
      +column_types:
        archived_at: timestamp
        created_at: timestamp 
        data_protection_contact_expires_at: timestamp
        data_protection_store_expires_at: timestamp
        last_advanced_at: timestamp
        last_interaction_at: timestamp
        snoozed_until: timestamp
        updated_at: timestamp 
        id: "{{ 'string' if target.name == 'bigquery' else 'varchar' }}"
    opportunity_stage_history:
      +column_types:
        updated_at: timestamp
    posting:
      +column_types:
        created_at: timestamp
        updated_at: timestamp
    posting_tag:
      +quote_columns: "{{ true if target.type == 'redshift' else false }}"
    requisition:
      +column_types:
        created_at: timestamp
    template_field:
      +column_types:
        field_index: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    user:
      +column_types:
        created_at: timestamp
        deactivated_at: timestamp
        id: "{{ 'string' if target.name == 'bigquery' else 'varchar' }}"
    opportunity_tag:
      +quote_columns: "{{ true if target.type == 'redshift' else false }}"
    contact_phone:
      +column_types:
        index: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        value: "{{ 'string' if target.name == 'bigquery' else 'varchar' }}"
    contact_link:
      +column_types:
        contact_id: "{{ 'string' if target.name == 'bigquery' else 'varchar' }}"
        link: "{{ 'string' if target.name == 'bigquery' else 'varchar' }}"
    resume:
      +column_types:
        id: "{{ 'string' if target.name == 'bigquery' else 'varchar' }}"
        file_ext: "{{ 'string' if target.name == 'bigquery' else 'varchar' }}"
        created_at: timestamp
        file_uploaded_at: timestamp
    stage:
      +column_types:
        id: "{{ 'string' if target.name == 'bigquery' else 'varchar' }}"