name: 'lever_integration_tests'
version: 0.6.0
config-version: 2
profile: 'integration_tests'
vars:
  lever_schema: lever_integration_tests
  lever_source:
    lever_application_identifier: "application"
    lever_archive_reason_identifier: "archive_reason"
    lever_feedback_form_identifier: "feedback_form"
    lever_feedback_form_field_identifier: "feedback_form_field"
    lever_interview_feedback_identifier: "interview_feedback"
    lever_interview_identifier: "interview"
    lever_interviewer_user_identifier: "interviewer_user"
    lever_offer_identifier: "offer"
    lever_opportunity_source_identifier: "opportunity_source"
    lever_opportunity_stage_history_identifier: "opportunity_stage_history"
    lever_opportunity_tag_identifier: "opportunity_tag"
    lever_opportunity_identifier: "opportunity"
    lever_posting_interview_identifier: "posting_interview"
    lever_posting_tag_identifier: "posting_tag"
    lever_posting_identifier: "posting"
    lever_requisition_posting_identifier: "requisition_posting"
    lever_requisition_offer_identifier: "requisition_offer"
    lever_requisition_identifier: "requisition"
    lever_stage_identifier: "stage"
    lever_user_identifier: "user"
    lever_contact_email_identifier: "contact_email"
    lever_contact_phone_identifier: "contact_phone"
    lever_contact_link_identifier: "contact_link"
    lever_resume_identifier: "resume"
  lever:
    application: "{{ ref('stg_lever__application') }}"
    archive_reason: "{{ ref('stg_lever__archive_reason') }}"
    feedback_form: "{{ ref('stg_lever__feedback_form') }}"
    feedback_form_field: "{{ ref('stg_lever__feedback_form_field') }}"
    interview_feedback: "{{ ref('stg_lever__interview_feedback') }}"
    interview: "{{ ref('stg_lever__interview') }}"
    interviewer_user: "{{ ref('stg_lever__interviewer_user') }}"
    offer: "{{ ref('stg_lever__offer') }}"
    opportunity_source: "{{ ref('stg_lever__opportunity_source') }}"
    opportunity_stage_history: "{{ ref('stg_lever__opportunity_stage_history') }}"
    opportunity_tag: "{{ ref('stg_lever__opportunity_tag') }}"
    opportunity: "{{ ref('stg_lever__opportunity') }}"
    posting_interview: "{{ ref('stg_lever__posting_interview') }}"
    posting_tag: "{{ ref('stg_lever__posting_tag') }}"
    posting: "{{ ref('stg_lever__posting') }}"
    requisition_posting: "{{ ref('stg_lever__requisition_posting') }}"
    requisition_offer: "{{ ref('stg_lever__requisition_offer') }}"
    requisition: "{{ ref('stg_lever__requisition') }}"
    stage: "{{ ref('stg_lever__stage') }}"
    user: "{{ ref('stg_lever__user') }}"
    contact_email: "{{ ref('stg_lever__contact_email') }}"
    contact_phone: "{{ ref('stg_lever__contact_phone') }}"
    contact_link: "{{ ref('stg_lever__contact_link') }}"
    resume: "{{ ref('stg_lever__resume') }}"
seeds:
  lever_integration_tests:
    +column_types:
      _fivetran_synced: timestamp
    application:
      +column_types:
        archived_at: timestamp
        created_at: timestamp
    feedback_form:
      +column_types:
        completed_at: timestamp
        created_at: timestamp
        deleted_at: timestamp
    feedback_form_field:
      +column_types:
        field_index: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        value_index: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        value_date: timestamp
        value_decimal: numeric
    interview:
      +column_types:
        canceled_at: timestamp
        created_at: timestamp
        date: timestamp
        duration: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    offer:
      +column_types:
        created_at: timestamp
    opportunity:
      +column_types:
        archived_at: timestamp
        created_at: timestamp
        data_protection_contact_expires_at: timestamp
        data_protection_store_expires_at: timestamp
        last_advanced_at: timestamp
        last_interaction_at: timestamp
        snoozed_until: timestamp
        updated_at: timestamp
        id: "{{ 'string' if target.name == 'bigquery' else 'varchar' }}"
    opportunity_stage_history:
      +column_types:
        updated_at: timestamp
        stage_id: "{{ 'string' if target.name == 'bigquery' else 'varchar' }}"
        opportunity_id: "{{ 'string' if target.name == 'bigquery' else 'varchar' }}"
        updater_id: "{{ 'string' if target.name == 'bigquery' else 'varchar' }}"
    posting:
      +column_types:
        created_at: timestamp
        updated_at: timestamp
    posting_tag:
      +quote_columns: "{{ true if target.type == 'redshift' else false }}"
    requisition:
      +column_types:
        created_at: timestamp
    user:
      +column_types:
        created_at: timestamp
        deactivated_at: timestamp
        id: "{{ 'string' if target.name == 'bigquery' else 'varchar' }}"
    opportunity_tag:
      +quote_columns: "{{ true if target.type == 'redshift' else false }}"
    contact_phone:
      +column_types:
        index: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        value: "{{ 'string' if target.name == 'bigquery' else 'varchar' }}"
    contact_link:
      +column_types:
        contact_id: "{{ 'string' if target.name == 'bigquery' else 'varchar' }}"
        link: "{{ 'string' if target.name == 'bigquery' else 'varchar' }}"
    resume:
      +column_types:
        id: "{{ 'string' if target.name == 'bigquery' else 'varchar' }}"
        file_ext: "{{ 'string' if target.name == 'bigquery' else 'varchar' }}"
        created_at: timestamp
        file_uploaded_at: timestamp
    stage:
      +column_types:
        id: "{{ 'string' if target.name == 'bigquery' else 'varchar' }}"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']